language: node_js
services:
- docker
cache:
  directories:
  - $HOME/.npm
notifications:
  email: false
node_js: 8
before_install:
<<<<<<< HEAD
- ./travis-update-docker.sh
=======
- npm install -g npm@5.2.0
>>>>>>> parent of c4297be... test: faster builds maybe
install: npm install
after_success: npm run deploy

# Trigger a push build on master and greenkeeper branches + PRs build on every branches
# Avoid double build on PRs (See https://github.com/travis-ci/travis-ci/issues/1147)
branches:
  only:
    - master
    - /^greenkeeper.*$/
